version: "3.9"
services:
  # Activate telegraf with its configuration file
  telegraf:
    image: telegraf:latest
    environment:
      # Common parameters
      - node_name=adult
      - logs_path=/logs
      - bucket=SN
      # Local InfluxDB OSS parameters (to be overridden with Influx DB Cloud)
      - url=http://influxdb:8086
      - token=GYQamYfyV46350EY0EBw7bVPUzVQGXz6qUEGkV3BFdchJJ0IPOn1xTpV-HkhJV3NaJ-Jb1MGi9w_Zk9gmcaL1w==
      - organization=MyOrg
    entrypoint: telegraf --config /etc/telegraf/telegraf.toml --debug
    deploy:
      replicas: 1
    # Hostname inside stack
    hostname: telegraf
    networks:
      - influxdb_net
    volumes:
      - ./telegraf-data/:/etc/telegraf/
      # Select one test case:
      # - ../docker_tmp/logs/1/:/logs # Elder
      - ../docker_tmp/logs/8/:/logs # Adult
networks:
  influxdb_net:
    external: true
