version: "3.9"
services:
  # Activate telegraf with its configuration file
  telegraf:
    image: telegraf:latest
    # Add --test for debugging
    entrypoint: telegraf --config /etc/telegraf/telegraf.toml --debug
    deploy:
      replicas: 1
    # Hostname inside stack
    hostname: telegraf
    networks:
      - influxdb_net
    volumes:
      - ./telegraf:/etc/telegraf/
      - ./logs:/logs
networks:
  influxdb_net:
    external: true
