version: '3'
services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminadmin
      - GF_INSTALL_PLUGINS=
    networks:
      - influxdb_net
    depends_on:
      - influxdb
networks:
  influxdb_net:
    external: true
