version: "3.9"
services:
  # Activate telegraf with its configuration file
  telegraf:
    image: telegraf:latest
    entrypoint: telegraf --config /etc/telegraf/telegraf.toml --debug
    deploy:
      replicas: 1
    # Hostname inside stack
    hostname: telegraf
    networks:
      - influxdb_net
    volumes:
      - ./telegraf/:/etc/telegraf/
      # Select one test case:
      # ./logs-local-0/:/logs # Genesis
      # ./logs-local-1/:/logs # Elder
      - ./logs-local-8/:/logs # Adult
networks:
  influxdb_net:
    external: true
