version: "3.9"
services:
  # Creates a local InfluxDB server
  influxdb:
    image: influxdb:latest
    deploy:
      replicas: 1
    # Hostname inside stack
    hostname: influxdb
    networks:
      - net
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=MyOrg 
      - DOCKER_INFLUXDB_INIT_BUCKET=SN
      - INFLUXD_REPORTING_DISABLED=true
networks:
  # Creates a network named influxdb_net (service name + '_' + network name)
  net:
    driver: overlay
